[basic]
season = summer

[temperature]
ideal      = 20
ideal_low  = 10
ideal_high = 30
max        = 35
min        = 0
step_weight = 10
tri_weight  = 1

[cloud]
ideal      = 0
ideal_low  = 0
ideal_high = 100
tri_weight = 0.4

[windspeed]
ideal      = 0
ideal_low  = 0
ideal_high = 30
max        = 60
min        = 0
step_weight = 10
tri_weight  = 0.6

[precipitation]
ideal      = 0
ideal_low  = 0
ideal_high = 5
max        = 20
min        = 0
step_weight = 10
tri_weight  = 1
