[basic]
season = summer

[temperature]
ideal      = 18
ideal_low  = 5
ideal_high = 25
max        = 30
min        = 0
step_weight = 6
tri_weight  = 1

[cloud]
ideal      = 0
ideal_low  = 0
ideal_high = 100
tri_weight = 1

[windspeed]
ideal      = 0
ideal_low  = 0
ideal_high = 30
max        = 60
min        = 0
step_weight = 5
tri_weight  = 1

[precipitation]
ideal      = 0
ideal_low  = 0
ideal_high = 0.5
max        = 1
min        = 0
step_weight = 10
tri_weight  = 1
