[basic]
season = winter

[temperature]
ideal      = -8
ideal_low  = -15
ideal_high = -1
max        = 5
min        = -20
step_weight = 10
tri_weight  = 1

[cloud]
ideal      = 0
ideal_low  = 0
ideal_high = 100
tri_weight = 0.4

[windspeed]
ideal      = 0
ideal_low  = 0
ideal_high = 30
max        = 60
min        = 0
step_weight = 10
tri_weight  = 0.6

[precipitation]
ideal      = 0
ideal_low  = 0
ideal_high = 15
max        = 20
min        = 0
step_weight = 2
tri_weight  = 1
